name: CI for learnk8scsi

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Docker version
        run: docker --version

      - name: Build the Docker image
        run: docker build -t devesh77388/learnk8scsi:${{ github.run_number }} .

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push devesh77388/learnk8scsi:${{ github.run_number }}

      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|image: devesh77388/learnk8scsi:.*|image: devesh77388/learnk8scsi:${{ github.run_number }}|" k8sfiles/deploycsi.yaml

      - name: Commit and push updated manifest
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add  k8sfiles/deploycsi.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main


  