name: CI for learnk8sCSI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Docker version
        run: docker --version

      - name: Build the Docker image
        run: docker build -t devesh77388/learnk8sCSI:${{ github.run_number }} .

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push devesh77388/learnk8sCSI:${{ github.run_number }}

      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|image: devesh77388/learnk8sCSI:.*|image: devesh77388/learnk8sCSI:${{ github.run_number }}|" k8sfiles/deploycsi.yaml

      - name: Commit and push updated manifest
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push origin main
